#!/bin/sh

# THIS FILE WAS AUTOMATICALLY CREATED #
# EDIT AT OWN RISK #

exec 2>&1

if [ `id -u` -eq 0 ]; then
   exec setuidgid minecraft $0
fi

dir='ENV'
[ -d $dir ] || mkdir $dir
exec envdir $dir ./start_minecraft
