#!/bin/sh

# does named pipe name exist but not a named pipe?
# create named pipe, if it doesn't already
# trap signals
# start server, listening to named pipe for commands
# poll for signals

# does server.jar exist as a symlink?

# failure modes: log, touch down, and svc -d
# If we merely log, when the problem is fixed the server will
# automatically start. This is a more reasonable behaivor.

# env Xms Xmx

exec 2>&1

FIFO=${FIFO:-commands}
JAVA=${JAVA:-java}
RAM=${RAM:-1024m}
RAM=${RAM:+-Xms$RAM -Xmx$RAM}
SERVER=${SERVER:-server.jar}

abort() {
    printf 'E: %s\n' "$@"
    exit 1
}

if [ -e "$FIFO" -a  ! -p "$FIFO" ]; then
    rm -f "$FIFO" || abort "$FIFO exists, and is not a named pipe"
fi

if [ ! -e "$FIFO" ]; then
    mkfifo "$FIFO" || abort "Cannot create $FIFO"
fi

# Does it have to be a symlink?
if [ ! -f "$SERVER" ]; then
    abort "$SERVER: no such file"
fi


# svc uses the following signals:
# -p STOP; -c CONT; -h HUP; -a ALRM; -i INT; -t TERM; -k KILL

# STOP/CONT are pretty useless for a server - will cause Can't keep up! warnings
# could use these to turn off/on automatic saves
# HUP and ALRM can be used to force a save of the world
# INT and TERM can be used to force a shutdown
# KILL, well, we can't do much about that, now, can we?

save() {
    printf 'save-all\n' > "$FIFO"
}

stop() {
    printf 'stop\n' > "$FIFO"
    wait $serverpid
    kill -kill $$
}

sig_hup() {
    save
}

sig_alrm() {
    save
}

sig_int() {
    stop
}

sig_term() {
    stop
}

trap -- sig_hup  HUP
trap -- sig_int  INT
trap -- sig_alrm ALRM
trap -- sig_term TERM

start() {
   # tail -f -n1 to read from the named pipe, and keep it open
   # kill -1 $$ to kill off the subshell when the java process
   #  ends. If the {} are removed, then the tail process will keep
   #  the pipeline open until something writes to the named pipe.
   #  using { java; kill; } ensures the kill gets processed as soon
   #  as the java process exits
   tail -F -n1 "$FIFO" | {
      "$JAVA" $RAM -jar "$SERVER" $JAVA_OPTS
      result=$?
      if [ $result -ne 0 ]; then
         printf 'W: Server exited with %d\n' $result
      fi
      kill -1 $$; # hang up on master monitoring shell
   }
}

start &
serverpid=$!

# process any incoming signals
while :; do
    sleep 1
    kill -0 $serverpid 2>/dev/null || break
done

echo Done.
